import jsPDF from 'jspdf';

export const exportToPDF = (itineraryData, formattedResponse, costSummary) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPos = 20;

  // Helper function to check if we need a new page
  const checkNewPage = (neededSpace = 20) => {
    if (yPos + neededSpace > pageHeight - 20) {
      doc.addPage();
      yPos = 20;
      return true;
    }
    return false;
  };

  // Header
  doc.setFillColor(255, 122, 45); // Primary color
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont(undefined, 'bold');
  doc.text('Travelly', 20, 20);

  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.text('AI-Powered Travel Itinerary', 20, 30);

  yPos = 50;

  // Trip Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.setFont(undefined, 'bold');
  const title = itineraryData?.title || 'Travel Itinerary';
  doc.text(title, 20, yPos);
  yPos += 15;

  // Trip Details Box
  doc.setFillColor(245, 245, 245);
  doc.rect(15, yPos, pageWidth - 30, 40, 'F');

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);

  const details = [
    `📍 Location: ${itineraryData?.location || 'N/A'}`,
    `👥 Travelers: ${itineraryData?.participants || 'N/A'} people`,
    `💰 Budget: $${itineraryData?.budget || 'N/A'}`,
    `🎯 Type: ${itineraryData?.type || 'N/A'}`,
    `📅 Dates: ${itineraryData?.startDate || 'N/A'} to ${itineraryData?.endDate || 'N/A'}`,
  ];

  details.forEach((detail, i) => {
    doc.text(detail, 20, yPos + 10 + (i * 7));
  });

  yPos += 50;

  // Day-by-Day Itinerary
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('Day-by-Day Itinerary', 20, yPos);
  yPos += 10;

  formattedResponse.forEach((day, dayIndex) => {
    checkNewPage(60);

    // Day Header
    doc.setFillColor(255, 122, 45);
    doc.rect(15, yPos, pageWidth - 30, 10, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(day.title, 20, yPos + 7);
    yPos += 15;

    // Activities
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');

    day.items.forEach((item, itemIndex) => {
      checkNewPage(15);

      // Activity bullet
      doc.setFillColor(255, 122, 45);
      doc.circle(18, yPos - 2, 1.5, 'F');

      // Activity text (wrap if too long)
      const lines = doc.splitTextToSize(item, pageWidth - 50);
      lines.forEach((line, lineIndex) => {
        if (lineIndex > 0) checkNewPage(7);
        doc.text(line, 25, yPos);
        yPos += 7;
      });

      yPos += 3; // Extra spacing between activities
    });

    yPos += 10; // Extra spacing between days
  });

  // Cost Summary
  if (costSummary && costSummary.length > 0) {
    checkNewPage(80);

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Budget Breakdown', 20, yPos);
    yPos += 10;

    doc.setFillColor(245, 245, 245);
    const summaryHeight = costSummary.length * 8 + 10;
    doc.rect(15, yPos, pageWidth - 30, summaryHeight, 'F');

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);

    costSummary.forEach((item, i) => {
      doc.text(`• ${item}`, 20, yPos + 10 + (i * 8));
    });

    yPos += summaryHeight + 10;
  }

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Travelly - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const filename = `${itineraryData?.title?.replace(/[^a-z0-9]/gi, '_') || 'itinerary'}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};

export const shareViaEmail = (itineraryData, formattedResponse, costSummary) => {
  const subject = encodeURIComponent(itineraryData?.title || 'Travel Itinerary');

  let body = `${itineraryData?.title || 'Travel Itinerary'}\n\n`;
  body += `Location: ${itineraryData?.location || 'N/A'}\n`;
  body += `Travelers: ${itineraryData?.participants || 'N/A'} people\n`;
  body += `Budget: $${itineraryData?.budget || 'N/A'}\n`;
  body += `Dates: ${itineraryData?.startDate || 'N/A'} to ${itineraryData?.endDate || 'N/A'}\n\n`;
  body += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n';

  formattedResponse.forEach((day) => {
    body += `${day.title}\n`;
    body += '─────────────────────\n';
    day.items.forEach((item) => {
      body += `• ${item}\n`;
    });
    body += '\n';
  });

  if (costSummary && costSummary.length > 0) {
    body += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    body += 'BUDGET BREAKDOWN\n';
    body += '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
    costSummary.forEach((item) => {
      body += `• ${item}\n`;
    });
  }

  body += '\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';
  body += 'Generated by Travelly - AI-Powered Travel Planner\n';

  const encodedBody = encodeURIComponent(body);
  window.location.href = `mailto:?subject=${subject}&body=${encodedBody}`;
};
